### Linear Regression

In [227]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [228]:
data = pd.read_csv(r"C:\Users\Lenovo\OneDrive\Desktop\nandu\shokam\ictak\car_age_price.csv")

In [229]:
data.head()

Year   Price
0  2018  465000
1  2019  755000
2  2019  700000
3  2018  465000
4  2018  465000

In [230]:
data.shape

(112, 2)

In [231]:
data.isna().sum()

Year     0
Price    0
dtype: int64

In [232]:
x = data.drop(['Price'], axis =1)
y = data['Price']

In [233]:
from sklearn.model_selection import train_test_split


In [234]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.2,random_state = 42)

In [235]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [236]:
model = lr.fit(x_train,y_train)

In [237]:
predictions = model.predict(x_test)

In [238]:
predictions

array([600775.91252081, 505558.77690466, 553167.34471273, 553167.34471273,
       553167.34471273, 410341.6412885 , 505558.77690466, 553167.34471273,
       600775.91252081, 600775.91252081, 315124.50567235, 505558.77690466,
       410341.6412885 , 648384.48032889, 553167.34471273, 600775.91252081,
       315124.50567235, 410341.6412885 , 505558.77690466, 505558.77690466,
       505558.77690466, 505558.77690466, 505558.77690466])

In [239]:
from sklearn.metrics import mean_squared_error, r2_score

In [240]:
print('R Squared value =' , r2_score(y_test,predictions))

R Squared value = 0.36759313425902185


In [241]:
year_to_predict = pd.DataFrame([2022], columns=['Year'])

In [242]:
predicted_price = model.predict(year_to_predict)

In [243]:
predicted_price

array([743601.61594504])

### Polynomial

In [244]:
df = pd.read_csv(r"C:\Users\Lenovo\OneDrive\Desktop\nandu\shokam\ictak\car_age_price.csv")

In [245]:
df.head()

Year   Price
0  2018  465000
1  2019  755000
2  2019  700000
3  2018  465000
4  2018  465000

In [246]:
x  = df.drop(['Price'], axis =1)
y = df['Price']

In [247]:
x_train,x_test,y_train,y_test= train_test_split(x,y, test_size = 0.2, random_state = 42)

In [248]:
from sklearn.preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures(degree = 2)

In [249]:
x_poly = poly_features.fit_transform(x_train)

In [250]:
model = lr.fit(x_poly,y_train)

In [251]:
x_test_poly = poly_features.fit_transform(x_test)

In [252]:
predictions = model.predict(x_test_poly)

In [253]:
print(' Mean Squared Error =' , mean_squared_error(y_test, predictions))
print('R Squared value =' , r2_score(y_test,predictions))

 Mean Squared Error = 4257698271.852013
R Squared value = 0.3777083533708031


In [254]:
year_to_predict = pd.DataFrame([2022], columns=['Year'])

In [255]:
year_to_predict_poly = poly_features.transform(year_to_predict)

In [256]:
predicted_price

array([743601.61594504])

In [257]:
poly_features1 = PolynomialFeatures(degree = 3)
x_poly1 = poly_features1.fit_transform(x_train)

In [258]:
lr = LinearRegression()
model1 = lr.fit(x_poly1,y_train)

In [259]:
x_test_poly1 = poly_features1.fit_transform(x_test)

In [260]:
predictions = model1.predict(x_test_poly1)

In [261]:
print('R Squared value =' , r2_score(y_test,predictions))

R Squared value = 0.31821164351789444


### Lasso

In [269]:
data = pd.read_csv(r"C:\Users\Lenovo\OneDrive\Desktop\nandu\shokam\ictak\car_age_price.csv")

In [270]:
x = data.drop(['Price'], axis =1)
y = data['Price']

In [271]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.3,random_state = 42)

In [272]:
from sklearn import linear_model
lasso_reg = linear_model.Lasso(alpha = 50, max_iter = 100, tol = 0.1)
model = lasso_reg.fit(x_train,y_train)

In [273]:
predictions = model.predict(x_test)

In [274]:
predictions


array([598846.43235704, 505703.32416816, 552274.87826259, 552274.87826259,
       552274.87826259, 412560.21597928, 505703.32416816, 552274.87826259,
       598846.43235704, 598846.43235704, 319417.1077904 , 505703.32416816,
       412560.21597928, 645417.98645148, 552274.87826259, 598846.43235704,
       319417.1077904 , 412560.21597928, 505703.32416816, 505703.32416816,
       505703.32416816, 505703.32416816, 505703.32416816, 505703.32416816,
       505703.32416816, 505703.32416816, 412560.21597928, 412560.21597928,
       365988.66188483, 412560.21597928, 505703.32416816, 598846.43235704,
       552274.87826259, 505703.32416816])

In [275]:
print('R Squared Value =' , r2_score(y_test, predictions))

R Squared Value = 0.4889279614672908
